// # Code generated by Elang Compiler
#include<bits/stdc++.h>
class ProgramLoader{public:ProgramLoader();~ProgramLoader();public:void Run();private:void dctl(float r);};
ProgramLoader::ProgramLoader(){}ProgramLoader::~ProgramLoader(){}void ProgramLoader::Run(){float t=10;dctl(10);float c=10;while(c>0){if(c==5){}else{}c=c-1;}}
void ProgramLoader::dctl(float r){if(10>5){if(10>5){std::cout<<"Hello Threre!";}}}
int main(int argc, char* argv[]){auto startup=new ProgramLoader();startup->Run();return EXIT_SUCCESS;}