// # Code generated by Elang Compiler
#include<bits/stdc++.h>
class ProgramLoader{public:ProgramLoader();~ProgramLoader();public:void Run();private:void print(std::string);std::string readline(std::string);void sysexec(std::string);private:};
ProgramLoader::ProgramLoader(){}ProgramLoader::~ProgramLoader(){}void ProgramLoader::Run(){std::string t=readline("Digite algo: \n");print("Resposta: "+t);}
void ProgramLoader::print(std::string __text__){std::cout<<__text__;}std::string ProgramLoader::readline(std::string __text__=""){std::string buffer;if(!__text__.empty())std::cout<<__text__;std::getline(std::cin,buffer);return buffer;}void ProgramLoader::sysexec(std::string __text__){system(__text__.c_str());}
int main(int argc, char* argv[]){auto startup=new ProgramLoader();startup->Run();return EXIT_SUCCESS;}