 // # DEFINITIONS

<digit> ::=
	  0-9

<alpha> ::=
	  a-zA-Z

<identifier> ::= 
	  <alpha>
	| <alpha><digit>

<type> ::=
	  int
	| char
	| void
	| bool
	| text
	| float

// # GRAMMAR

<variable-declaration> ::= 
	  var : <type> <identifier> ;
	| var : <type> <identifier> = <expression> ;
	| var : <type> <identifier> = "bind of type data" ;
	| var : <type> [ <digit> ] <identifier> ;
	| var : <type> [ <digit> ] <identifier> = { "bind of type data", "bind of type data" } ;

<expression> ::= 
	   <expression>
	|  <digit> + | - | * | / <digit>
	|  <digit> + | - | * | / <identifier>
	|  <digit> + | - | * | / <expression>

<function-declaration> ::=
	   fun : <type> <identifier> ( ) { }
	|  fun : <type> <identifier> ( <list-variable-declaration> ) { <expression> }
	