// # Code generated by Elang Compiler
#include<bits/stdc++.h>
class ProgramLoader{public:ProgramLoader();~ProgramLoader();public:void Run();private:};
ProgramLoader::ProgramLoader(){}ProgramLoader::~ProgramLoader(){}void ProgramLoader::Run(){}
int main(int argc, char* argv[]){auto startup=new ProgramLoader();startup->Run();return EXIT_SUCCESS;}