// # Code generated by Elang Compiler
// # Licensed under Apache 2.0
#include<bits/stdc++.h>
class __elang_class_runnable_cxx{private:public:__elang_class_runnable_cxx();~__elang_class_runnable_cxx();public:void __elang_run_body_cxx();private:int sum(int n1,int n2);};
__elang_class_runnable_cxx::__elang_class_runnable_cxx(){}__elang_class_runnable_cxx::~__elang_class_runnable_cxx(){}void __elang_class_runnable_cxx::__elang_run_body_cxx(){std::cout<<sum(34,7)<<'\n';}
int __elang_class_runnable_cxx::sum(int n1,int n2){if(n1<5){n1=10;return n1;}else{return n2;}return n1+n2;}
int main(int argc, char* argv[]){auto startup=new __elang_class_runnable_cxx();startup->__elang_run_body_cxx();return EXIT_SUCCESS;}